name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        cache-version: 0
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Run RSpec tests
      run: |
        mkdir -p reports
        bundle exec rspec --format RspecJunitFormatter --out reports/rspec.xml --format documentation
    
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: rspec-reports
        path: ./reports
        retention-days: 5
    
    - name: Run Cucumber tests
      env:
        CI: true
        CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
      run: bundle exec cucumber

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download reports
      uses: actions/download-artifact@v4
      with:
        name: rspec-reports
        path: ./reports
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        publish_branch: gh-pages
        commit_message: "Update RSpec report"
        force_orphan: true
        enable_jekyll: false 