name: Publish Reports

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        cache-version: 0
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Run RSpec tests and generate report
      run: |
        mkdir -p reports
        bundle exec rspec --format RspecJunitFormatter --out reports/rspec.xml --format documentation
    
    - name: Prepare reports directory
      run: |
        echo '<!DOCTYPE html><html><head><title>RSpec Test Results</title><style>body{font-family:Arial,sans-serif;margin:20px;background-color:#f5f5f5}.container{max-width:1200px;margin:0 auto;background-color:white;padding:20px;border-radius:5px;box-shadow:0 2px 5px rgba(0,0,0,0.1)}h1{color:#333;border-bottom:2px solid #eee;padding-bottom:10px}.test-results{margin-top:20px}.test-case{margin:10px 0;padding:10px;border:1px solid #ddd;border-radius:3px}.passed{background-color:#e6ffe6;border-left:4px solid #4CAF50}.failed{background-color:#ffe6e6;border-left:4px solid #f44336}.timestamp{color:#666;font-size:0.9em;margin-top:20px}</style></head><body><div class="container"><h1>RSpec Test Results</h1><div class="test-results"><iframe src="rspec.xml" style="width:100%;height:800px;border:none;"></iframe></div><div class="timestamp">Last updated: <span id="timestamp"></span></div></div><script>document.getElementById("timestamp").textContent=new Date().toLocaleString();</script></body></html>' > reports/index.html
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        publish_branch: gh-pages
        commit_message: "Update RSpec report"
        force_orphan: true
        enable_jekyll: false 